### ISSUE TITLE
Stories instgaram 

### ISSUE THREAD

**Issue by ThisMe124** [9xN/node-ig-framework#12]
how can I get data from someone's stories? ( Seen stories)

**Comment by 9xN** [comment]
> how can I get data from someone's stories? ( Seen stories)

im not sure what exactly you mean? can you elaborate what you are trying to achieve exactly?

**Comment by ThisMe124** [comment]
> > how can I get data from someone's stories? ( Seen stories)
> 
> im not sure what exactly you mean? can you elaborate what you are trying to achieve exactly?

Seen a someone stories

**Comment by 9xN** [comment]
you can't? im still not sure what exactly you are asking sorry

**Comment by ThisMe124** [comment]
> you can't? im still not sure what exactly you are asking sorry

I want to ask if there is a function?

**Comment by 9xN** [comment]
> > you can't? im still not sure what exactly you are asking sorry
> 
> I want to ask if there is a function?

i dont think there is for what you want to do

**Comment by ThisMe124** [comment]
> > > you can't? im still not sure what exactly you are asking sorry
> > 
> > 
> > I want to ask if there is a function?
> 
> i dont think there is for what you want to do

I want to take is the media in someone's stories

**Comment by 9xN** [comment]
> > > > you can't? im still not sure what exactly you are asking sorry
> > > 
> > > 
> > > I want to ask if there is a function?
> > 
> > 
> > i dont think there is for what you want to do
> 
> I want to take is the media in someone's stories

no not possible then unless you add that feature yourself using private instagram api wrapper

**Comment by ThisMe124** [comment]
> > > > > you can't? im still not sure what exactly you are asking sorry
> > > > 
> > > > 
> > > > I want to ask if there is a function?
> > > 
> > > 
> > > i dont think there is for what you want to do
> > 
> > 
> > I want to take is the media in someone's stories
> 
> no not possible then unless you add that feature yourself using private instagram api wrapper

Oh ok, thanks for reply :)
