### ISSUE TITLE
Error code 400, my bot was working perfectly just add some new code it dead

### ISSUE THREAD

**Issue by CycloneAddons** [9xN/node-ig-framework#13]
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

IgResponseError: POST /api/v1/accounts/login/ - 400 Bad Request; Please wait a few minutes before you try again.
    at Request.handleResponseError (/data/data/com.termux/files/home/node_modules/instagram-private-api/dist/core/request.js:126:16)
    at Request.send (/data/data/com.termux/files/home/node_modules/instagram-private-api/dist/core/request.js:54:28)

**Comment by 9xN** [comment]
thats not the bots problem or issue thats instagram rate limiting you just wait a day or so and try again

**Comment by CycloneAddons** [comment]
Is there any way to send custom error in chat because I try everything it send error of .sendPhoto in console and kill the bot

Literally i tried everything thing

**Comment by 9xN** [comment]
> Is there any way to send custom error in chat because I try everything it send error of .sendPhoto in console and kill the bot
> 
> Literally i tried everything thing

can you open a new issue and elaborate and send some logs of this? ill look into it
