### ISSUE TITLE
Status code 503

### ISSUE THREAD

**Issue by CycloneAddons** [9xN/node-ig-framework#14]
How to send.custom error

**Comment by CycloneAddons** [comment]
[https://cdn.discordapp.com/attachments/1098230444492857404/1125015791809601606/Screenshot_2023-07-01-17-39-55-464_com.replit.app.jpg](url)

**Comment by CycloneAddons** [comment]
![Uploading Screenshot_2023-07-01-17-39-55-464_com.replit.app.jpg…]()

**Comment by CycloneAddons** [comment]
![Screenshot_2023-07-01-17-39-55-464_com replit app](https://github.com/9xN/node-ig-framework/assets/90061864/0cefa762-5b16-4571-b867-728e96119ddd)

**Comment by CycloneAddons** [comment]
And can I make command handler like Discordjs

**Comment by 9xN** [comment]
> And can I make command handler like Discordjs

yes ive actually gone ahead and done this in my personal instagram bot and im not sure if i mentioend in the readme but instagram has blocked replits proxy ips from connecting or interacting with their services so youll either have to local host or use a unblocked vps to host the bot if its not on the readme already ill add it right away

**Comment by CycloneAddons** [comment]
It command handler possible in current version

**Comment by 9xN** [comment]
> It command handler possible in current version

yes

**Comment by CycloneAddons** [comment]
Ohky! I have one more question how to fetch message of the chat like discord.

**Comment by 9xN** [comment]
what do you mean?

**Comment by 9xN** [comment]
here read this it might help: 
https://insta.js.org/#/docs/main/master/class/Message

**Comment by CycloneAddons** [comment]
Umm I mean to fetch chats messages like 10 user messages and 10 bot message which they send

**Comment by 9xN** [comment]
> Umm I mean to fetch chats messages like 10 user messages and 10 bot message which they send

yes you can do that using the chat id it shows you how in that documentation site as well just look through it, keep in mind thats a older and outdated and worse version of this wrapper but the methods are the same for the most part
