### ISSUE TITLE
newFollower Not working 

### ISSUE THREAD

**Issue by CycloneAddons** [9xN/node-ig-framework#15]
client.on("newFollower", async (user) => {
  user.follow();
  console.log(user.username)
});

**Comment by 9xN** [comment]
can you provide an error message or what exactly you mean by not working? does it just not log when someone follows you?

**Comment by CycloneAddons** [comment]
No it not logging or throwing any error 😕

**Comment by 9xN** [comment]
> No it not logging or throwing any error 😕

then perhaps your implementation is incorrect i dont seem to be having any issues what so ever running identical code on my end im sorry but without more information im not entirely sure how i could help

**Comment by CycloneAddons** [comment]
Can You Check It In Your Own Bot

**Comment by CycloneAddons** [comment]
Bcz it was working 2 month ago

**Comment by 9xN** [comment]
> Can You Check It In Your Own Bot

i will check again

**Comment by 9xN** [comment]
nevermind you are correct it is not working for me either i will look into this more when i have time

**Comment by CycloneAddons** [comment]
Hm as soon as possible

**Comment by CycloneAddons** [comment]
![Screenshot_2023-08-13-21-08-30-871_com replit app](https://github.com/9xN/node-ig-framework/assets/90061864/c0a46ff9-5a2f-40d4-8fef-7283af0437eb)

```js
client.on('messageCreate', message => {
    message.chat.sendMessage("hello 👋")
    console.log(message.user.fetchFollowing());
});
```
Why fetchFollowing Not Working 

I just only want to know is user follow the client or not 

Any other method to know user follow or not

**Comment by 9xN** [comment]
the bot doesnt work on replit

**Comment by 9xN** [comment]
> Hm as soon as possible

im busy and going on vacation i looked into this more and it will be a lot of work its not even an issue related to the private insta api thats been addressed so it will be a lot of work to fix

**Comment by CycloneAddons** [comment]
> the bot doesnt work on replit

Bro it working on replit I m using from 3 months. Just tell me how to fetch follower

**Comment by 9xN** [comment]
> > the bot doesnt work on replit
> 
> Bro it working on replit I m using from 3 months. Just tell me how to fetch follower

ok well it hasnt been workin on replit in over 3 years so kudos to you for getting it to work

**Comment by 9xN** [comment]
if you want to have a more in depth conversion add me on discord: 44xo
