### ISSUE TITLE
Create the equivalent of the chat.awaitMessage of discord.js

### ISSUE THREAD

**Issue by gaetan20** [9xN/node-ig-framework#19]
Hello, I findyour repo really usefull but in my opinion a function that while wait for a message is missing. Or maybe there's another way to do. If so, could you please explain me how to do this.

My goal is to create a quizz that while ask questions and then give a recap of the answers.

Thanks by advance for your help !

**Comment by 9xN** [comment]
> Hello, I findyour repo really usefull but in my opinion a function that while wait for a message is missing. Or maybe there's another way to do. If so, could you please explain me how to do this.
> 
> My goal is to create a quizz that while ask questions and then give a recap of the answers.
> 
> Thanks by advance for your help !

hello! thank you for your interest in the project! there is a way you could implement this using the message collector for a set amount of time or unlimited and wait for a certain amount of messages to be received or other events then stop the collector

![librewolf_G4TJHXS9BM](https://github.com/9xN/node-ig-framework/assets/94141577/2f624291-c865-4ed5-80e6-c071bfa5b0c4)

Properties
.chat

The chat in which the messages should be collected
Type: Chat
.client

The client that instantiated this
Type: Client
.ended

Whether this collector is ended
Type: boolean
.filter

The filter to apply
Type: Function
.idle

How long to stop the collector after inactivity in milliseconds
Type: number
Methods
.end(reason)

End the collector
Parameter	Type	Description
reason	string

The reason the collector ended
Returns: void
Events

Emitted when the collector ends
Parameter	Type	Description
reason	Message

The reason the collector ended


Emitted when a message is collected by the collector
Parameter	Type	Description
message	Message

The collected message

**Comment by gaetan20** [comment]
Thank you ! i'll try that

**Comment by gaetan20** [comment]
Update : it works fine thank you !
Is there a way to collect likes ?

**Comment by 9xN** [comment]
> Update : it works fine thank you ! Is there a way to collect likes ?

Awesome! likes on a message? or a post?

**Comment by gaetan20** [comment]
on a message

**Comment by 9xN** [comment]
not using a collector but you can check the like count:
![image](https://github.com/9xN/node-ig-framework/assets/94141577/215f8cdc-72fe-4f3e-b9e2-16720b51131f)
![librewolf_5QhFrQkGMr](https://github.com/9xN/node-ig-framework/assets/94141577/263b99c6-b9aa-4870-bea8-bb4468c5c030)

**Comment by gaetan20** [comment]
ok thank you. Or maybe with the likeAdd event ?
