### ISSUE TITLE
 The username you entered doesn't appear to belong to an account. 

### ISSUE THREAD

**Issue by Strooss** [9xN/node-ig-framework#2]
im getting this error
`IgResponseError: POST /api/v1/accounts/login/ - 400 Bad Request; The username you entered doesn't appear to belong to an account. Please check your username and try again.`

**Comment by 9xN** [comment]
are you making sure to enter in a valid/correct username in the correct field? ie; proper spelling and capitalization? make sure to replace the fields when calling client with your actual username and password and dont remove the quotes;

```js
client.login('username', 'password');
```
so for example if your username and password for the account were root and admin you would put 

```js
client.login('root', 'admin');
```

**Comment by Strooss** [comment]
Thank you for your reply!
Yes I'm aware of that. also i tried ré-checking the informations and also log-in in instagram with that name and password and it log me in..
In Conclusion, the problem as i see is from the package.
Please keep me updates for any news.

**Comment by 9xN** [comment]
hm can you send me your platform information youre trying to run the program on as well as a copy of your source code and how you are using the library? an error message copy paste would help as well!
