### ISSUE TITLE
Node restarting all the time after install node-ig-framework

### ISSUE THREAD

**Issue by Matheus-Lima-Moreira** [9xN/node-ig-framework#20]
![Captura de tela 2024-01-18 155440](https://github.com/9xN/node-ig-framework/assets/87667337/51fc87ec-7765-4085-b6a7-1eaa355ad092)

I trying to use this lib because insta.js is dead and here apparently we have some fix and people who contribute, but when i install this lib i have a loop of my node backend application restarting, does anyone know why?

**Comment by Matheus-Lima-Moreira** [comment]
I commented the following line in Client.js and it worked:

![Captura de tela 2024-01-18 165830](https://github.com/9xN/node-ig-framework/assets/87667337/9dff4b2d-5594-450c-bb9f-4cece65b2b0c)

**Comment by Matheus-Lima-Moreira** [comment]
Does anyone know what this line is for?
From what I understand, is it to save a cache of the Client state?
Can we make this dynamic by some parameter?

**Comment by 9xN** [comment]
> Does anyone know what this line is for? From what I understand, is it to save a cache of the Client state? Can we make this dynamic by some parameter?

I have no idea anymore I have not worked on this project in a while since instagram had a major re-haul of their api once again breaking lots of features.
If you want to look into this further and work on a solution or implement a dynamic alternative be my guest I will gladly accept pull requests
