### ISSUE TITLE
show errors in the console

### ISSUE THREAD

**Issue by pedroaf0** [9xN/node-ig-framework#27]
Interestingly, the library worked very well for a whole afternoon, today it simply doesn't work anymore, there is no error message or anything. Simply running the example code returns nothing.

tested on gitpod.io and windows 10

**Comment by pedroaf0** [comment]
Apparently the problem was that Instagram blocked my account.

The library needs to show errors in the console

**Comment by 9xN** [comment]
not an issue…. pull requests are open and encouraged, add it yourself
