### ISSUE TITLE
Need Some Information.

### ISSUE THREAD

**Issue by adiiityaaa** [9xN/node-ig-framework#3]
1.  Does this work in the same way like that of Androz?
2.  Will Androz documentation work for this module?

**Comment by 9xN** [comment]
yes and yes i will document the changes myself when i feel as though enough changes have happened for now ive only gone ahead and update some old insecure dependencies and fixed a few things

**Comment by stafocher** [comment]
Parabéns pela iniciativa!

Grande potencial no projeto e abandono total do Androz.

**Comment by 9xN** [comment]
> Parabéns pela iniciativa!
> 
> Grande potencial no projeto e abandono total do Androz.

Muito Obrigado
