### ISSUE TITLE
Cannot read property "Subscribe"!

### ISSUE THREAD

**Issue by adiiityaaa** [9xN/node-ig-framework#4]
Faced a new error while running the package: 
![image](https://user-images.githubusercontent.com/77008828/220349341-449433ab-0f83-4f60-85e3-51f442fee925.png)

If I remove this line: ig.fbns.push$.subscribe((data) => this.handleFbnsReceive(data))
The bot logins but does not work anymore, like no events respond.

**Comment by 9xN** [comment]
interesting I have not seen this error before so I would have to do some testing & diagnostics, can you please provide your current source code file(s) as well as node environment/version info?

**Comment by adiiityaaa** [comment]
I currently don't have source code files. However, I am importing it as an ESM module. Also, my nose version is 16.19.1

**Comment by 9xN** [comment]
oh ok

**Comment by adiiityaaa** [comment]
I rdeleted the line, however it isnt triggering the messageCreate event.
What files do you need in Source code?

**Comment by 9xN** [comment]
hi small update on the situation im having the same issue now i will be doing a much deeper dive into this issue and will be trying to resolve it as soon as possible! in the mean time you can try downgrading to an older version of the wrapper from nmp by changing the version of this package in your package.json file to 0.0.1  and this might be a good temporary solution

**Comment by 9xN** [comment]
@adiiityaaa try updating to v1.0.5 or uninstall your node modules and from package.json or upgrade to v1.0.5 it is all working now again
