### ISSUE TITLE
I am using this in replit

### ISSUE THREAD

**Issue by CycloneAddons** [9xN/node-ig-framework#5]
![Screenshot_2023-03-07-13-33-21-984_com replit app](https://user-images.githubusercontent.com/90061864/223360984-6801c905-cd86-403a-9df9-46873875ffe2.jpg)

This error comming

**Comment by 9xN** [comment]
it doeesnt work on replit anymore as instagram blocks their proxied IP addresses and marks them as spam you either have to host this locally i.e: on a raspberry pi or home server, or your PC, OR you could try hosting on a different server or host or service that isnt blocked by instagram
